import Container from "../Container/Container";
import Subtitle from "../Main/Subtitle/Subtitle";
import Title from "../Main/Title/Title";
import img from "../../assets/aboutImg.png";
import img1 from "../../assets/aboutImg1.png";
import s from "./About.module.css";

const About = () => {
  return (
    <section className={s.about}>
      <Container>
        <div className={s.wrapper}>
          <div className={s.titleWrapper}>
            <Title text="A new wave of collectibles is about to hit the blockchain." />
          </div>
          <p className={s.subinfo}>
            Characterised by soft lighting, vintage colour schemes and quirky
            costumes, these generative 3D TinyFaces are the addition to your NFT
            collection you’ve been waiting for.
          </p>
        </div>

        <ul className={s.list}>
          <li className={s.item}>
            <img src={img1} alt="decorative image" width="533" height="445" />
            <div className={s.info}>
              <Subtitle text="About" />
              <Title text="Thousands of unique NFTs" />
              <p className={s.desc}>
                Each character is entirely unique and is generated by combining
                attributes such as colour palettes, skin tones, facial traits,
                outfits and accessories. With nearly endless combinations, all
                characters are guaranteed to be one of a kind.
              </p>
              <button type="button" className={s.button} data="Place a bid" />
            </div>
          </li>
          <li className={s.item}>
            <img src={img} alt="decorative image" width="533" height="455" />
            <div className={s.info}>
              <Subtitle text="About" />
              <Title text="Secure the most rare" />
              <p className={s.desc}>
                Even though no two Tinyfaces will ever be the same, some
                variations are rarer than others. Watch out for special
                accessories and raw materials - the rarer the attributes, the
                rarer your character will be.
              </p>
              <button type="button" className={s.button} data="Place a bid" />
            </div>
          </li>
        </ul>
      </Container>
    </section>
  );
};

export default About;
